[tool.poetry]
name = "ocr-testing"
version = "0.1.0"
description = ""
authors = ["andymiller-og <anm5030@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
streamlit = "^1.43.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
